[site]
name = "Anzu"
description = "Next-generation community engine, bring the conversation online."
url = "https://tryanzu.com/"
logoUrl = "/images/anzu.svg"
thirdPartyAuth = ["fb"]

[[site.nav]]
href = "/"
name = "Inicio"

[[site.nav]]
href = "/chat"
name = "Chat"

[[site.chat]]
name = "general"
description = "Anzu's general chat room"
youtube = "PUZn1I6llJs"